sudo: required
language: bash
servies:
    - docker

matrix:
    include:
    - os: osx
    - os: linux
      env: BUILD_FLAVOR=fedora
      arch:
        - amd64
        - ppc64le
    - os: linux
      env: BUILD_FLAVOR=ubuntu
      arch:
        - amd64
        - ppc64le   
    - os: linux
      env: BUILD_FLAVOR=debian
      arch:
        - amd64
        - ppc64le

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -f ./.travisci/Dockerfile.$BUILD_FLAVOR -t danmaq-devel . ; fi

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt ; fi

script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash ./.travisci/.travis.sh ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -it danmaq-devel ./.travisci/.travis.sh ; fi
